### ISSUE TITLE
Documentation not visible due to missing licenses

### ISSUE THREAD

**Issue by tmakar** [ElektraInitiative/go-elektra#18]
When following the `README.md` and visiting https://pkg.go.dev/go.libelektra.org/kdb (go documentation of elektra) there is no documentation visible. This seems to be the case because we did not provide any licenses in this repository (see picture below). 

I would suggest putting the same licensing folder into this go-elektra repository as we have in our libelektra repository. 

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/22303999/224477406-4330228b-e0c3-477c-a1ab-e66d28b3da2c.png">

**Comment by tmakar** [comment]
@kodebach @markus2330 

What do you think?

**Comment by kodebach** [comment]
Technically, we have to ask @raphi011 (who wrote the code). But since the binding was originally part of the main libelektra repository, I'd assume it's fine to use the same BSD-3-Clause license here.

**Comment by tmakar** [comment]
@markus2330 I can't assign myself to any issue in this repo. Can you please provide me access!

**Comment by markus2330** [comment]
> I would suggest putting the same licensing folder into this go-elektra repository as we have in our libelektra repository.

Yes, good idea, it is BSD licensed, like Elektra.

> Technically, we have to ask

I already said that the code must be BSD licensed when he started writing, like I said to everyone else, too. So it was just forgotten to add the information here.

elektradevelopers were added, so @tmakar you should be able to assign yourself.
